AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  S3entinel - Event-Driven Architecture
  S3 Bucket -> DynamoDB + Lambda Trigger

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java21
    Architectures:
      - x86_64

Resources:
  # The Warehouse (S3 Bucket)
  S3entinelBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 's3entinel-iac-${AWS::Region}-${AWS::AccountId}'
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, HEAD]
            AllowedOrigins: ['*']

  # The Memory (DynamoDB Table)
  S3entinelTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: S3entinel_Files_IaC
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # The Analyst (Lambda Function)
  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.codebymathabo.s3entinel.lambda.ImageProcessor::handleRequest
      Policies:
        # I use the name string instead of !Ref
        - S3ReadPolicy:
            BucketName: !Sub 's3entinel-iac-${AWS::Region}-${AWS::AccountId}'
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref S3entinelBucket
            Events: s3:ObjectCreated:*

Outputs:
  BucketName:
    Description: "S3 Bucket"
    Value: !Ref S3entinelBucket
  TableName:
    Description: "DynamoDB Table"
    Value: !Ref S3entinelTable
  LambdaFunction:
    Description: "Lambda Processor ARN"
    Value: !GetAtt ImageProcessorFunction.Arn